### ISSUE TITLE
Plugin fails in bulding stage

### ISSUE THREAD

**Issue by mromanuk** [xavierdutreilh/wintersmith-sitemap#1]
I'm using Wintersmith 2.1.0, the plugin is failing with:
```.../wintersmith-sitemap/lib/index.js:22
      return env.helpers.contents.list(contents).filter(function(content) {
                                  ^
TypeError: Cannot call method 'list' of undefined
    at Sitemap.getPages (/Users/martin/Sites/pixdeo.com/node_modules/wintersmith-sitemap/lib/index.js:22:35)
    at Sitemap.<anonymous> (/Users/martin/Sites/pixdeo.com/node_modules/wintersmith-sitemap/lib/index.js:39:21)
    at /usr/local/lib/node_modules/wintersmith/lib/core/renderer.js:44:19
    at process._tickCallback (node.js:442:13)
```

**Comment by xavierdutreilh** [comment]
@mromanuk, do you have a sample project where this error occurs? Are you sure that you have added the plugin to the `plugins` section of your `config.json` file?

**Comment by mromanuk** [comment]
If you want I can zip and send you my site, would be ok?
I'm certain that it's included in the plugins section in config.json:

```
  verbose registering content plugin JsonPage that handles: **/*.json
  verbose loading plugin: ./plugins/paginator.coffee
  verbose loading plugin: wintersmith-articles-helper
  verbose loading plugin: wintersmith-sitemap
  verbose loading plugin: wintersmith-tag
  rendering tree:

....
    sitemap.xml (url: /sitemap.xml)

  verbose render output directory: /Users/martin/Sites/pixdeo.com/build
  verbose writing content / to /Users/martin/Sites/pixdeo.com/build/index.html
  verbose writing content /tag/polo/1/ to /Users/martin/Sites/pixdeo.com/build/tag/polo/1/index.html
  verbose writing content /tag/polo%27s%20house/1/ to /Users/martin/Sites/pixdeo.com/build/tag/polo's house/1/index.html
  verbose writing content /tag/javascript/1/ to /Users/martin/Sites/pixdeo.com/build/tag/javascript/1/index.html
  verbose writing content /tag/prototypal%20inheritance/1/ to /Users/martin/Sites/pixdeo.com/build/tag/prototypal inheritance/1/index.html
  verbose writing content / to /Users/martin/Sites/pixdeo.com/build/index.html

/Users/martin/Sites/pixdeo.com/node_modules/wintersmith-sitemap/lib/index.js:22
      return env.helpers.contents.list(contents).filter(function(content) {
                                  ^
TypeError: Cannot call method 'list' of undefined
    at Sitemap.getPages (/Users/martin/Sites/pixdeo.com/node_modules/wintersmith-sitemap/lib/index.js:22:35)
    at Sitemap.<anonymous> (/Users/martin/Sites/pixdeo.com/node_modules/wintersmith-sitemap/lib/index.js:39:21)
    at /usr/local/lib/node_modules/wintersmith/lib/core/renderer.js:44:19
    at process._tickCallback (node.js:442:13)
```

**Comment by xavierdutreilh** [comment]
@mromanuk, I apologize. I did not read carefully and got confused between `wintersmith-sitemap` and `wintersmith-contents`.

Actually, `wintersmith-sitemap` depends on `wintersmith-contents` and I forgot to (1) specify the latter as a peer dependency in `wintersmith-sitemap` and (2) update the instructions in the README. I did these two actions in dd3c03ac2a27f4a33257141696f1b718418dfb7a and made a new release patch (` "wintersmith-sitemap": "0.1.4"`). Can you retry with this new version (and add `wintersmith-contents` to your `config.json` file) ?

**Comment by mromanuk** [comment]
@xavierdutreilh I did as you said, and it worked like a charm! 
thank you
